# Netlify configuration for Muhammad Sarim's Portfolio
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Gatsby builds to 'public')
  publish = "public"
  
  # Node.js version
  environment = { NODE_VERSION = "18", NPM_FLAGS = "--legacy-peer-deps", CI = "false" }

[build.processing]
  # Skip processing of images, JS, and CSS (Gatsby handles this)
  skip_processing = false

[build.processing.css]
  # Let Gatsby handle CSS optimization
  bundle = false
  minify = false

[build.processing.js]
  # Let Gatsby handle JS optimization
  bundle = false
  minify = false

[build.processing.html]
  # Let Gatsby handle HTML optimization
  pretty_urls = true

# Redirect rules for SPA behavior
[[redirects]]
  # Handle client-side routing (for Gatsby)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# 404 page redirect
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

# Specific headers for HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Headers for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (for your contact form)
[forms]
  # Enable Netlify Forms
  netlify = true

# Plugin configuration
[[plugins]]
  # Essential plugin for Gatsby
  package = "@netlify/plugin-gatsby"

# Environment-specific settings
[context.production]
  command = "npm run build"
  
[context.deploy-preview]
  command = "npm run build"

[context.branch-deploy]
  command = "npm run build"

# Development context (for testing)
[context.dev]
  command = "npm run develop"
  port = 8000
